import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'tools/render.js');
const RENDER = 'shared/render';

const inRender = readdirSync(join(ROOT, RENDER)).filter(f => /\.(cpp|h)$/.test(f)).sort()
  .map(f => `${RENDER}/${f}`);
const inputs = [...inRender, 'shared/aurora_protocol.h', 'tools/render-api.cpp'];
const sources = inputs.filter(f => f.endsWith('.cpp')).map(f => join(ROOT, f));

const EXPORTS = [
  'aurora_controls', 'aurora_pixels', 'aurora_pars', 'aurora_par_hue_places', 'aurora_fan', 'aurora_bend',
  'aurora_bend_points',
  'aurora_strip_count', 'aurora_par_count', 'aurora_pixels_per_strip', 'aurora_fan_curve_points',
  'aurora_motion_new', 'aurora_motion_copy', 'aurora_wall_new', 'aurora_wall_clear_tails',
  'aurora_render', 'aurora_palette_count', 'aurora_palette_name', 'aurora_palette_color', 'aurora_lfo_wave',
  'aurora_convert', 'aurora_lfo_period_beats',
  'aurora_control_at_strip', 'aurora_control_at_par', 'aurora_route_reach', 'aurora_route_refused',
  'aurora_wave_mean',
];

const FLAGS = [
  '-O2', '-std=c++17', '-fno-exceptions', '-fno-rtti',
  '-I', join(ROOT, 'shared'), '-I', join(ROOT, RENDER),
  '-sSINGLE_FILE=1', '-sSINGLE_FILE_BINARY_ENCODE=0', '-sMODULARIZE=1', '-sEXPORT_NAME=AuroraRenderModule',
  '-sENVIRONMENT=web,node', '-sFILESYSTEM=0',
  `-sEXPORTED_FUNCTIONS=${EXPORTS.map(n => '_' + n).join(',')}`,
  '-sEXPORTED_RUNTIME_METHODS=HEAPU8,HEAPF32',
];

const hash = createHash('sha256');
for (const f of inputs) hash.update(f).update(readFileSync(join(ROOT, f)));
hash.update(FLAGS.filter(f => !f.startsWith('/')).join(' '));
const digest = hash.digest('hex').slice(0, 16);
const HEADER = `// Generated by tools/build-render.mjs from shared/render. Do not edit.\n`
  + `// sources ${digest}\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { }
  if (!current.startsWith(HEADER)) {
    console.error('tools/render.js is out of date — run: node tools/build-render.mjs');
    process.exit(1);
  }
  console.log('tools/render.js up to date with shared/render');
} else {
  build();
}

function build() {
  const dir = mkdtempSync(join(tmpdir(), 'aurora-render-'));
  try {
    const built = join(dir, 'render.js');
    try {
      execFileSync('em++', [...FLAGS, ...sources, '-o', built], { stdio: 'inherit' });
    } catch {
      process.exitCode = 1;
      return;
    }
    writeFileSync(OUT, HEADER + readFileSync(built, 'utf8'));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
  console.log('tools/render.js written');
}
