#!/usr/bin/env node
//
// Emit tools/cc.js from shared/aurora_protocol.h, so the browser side reads
// the same numbers the firmware compiles against instead of a second copy of
// them.
//
//   node tools/gen-cc.mjs            rewrite tools/cc.js
//   node tools/gen-cc.mjs --check    fail if it is out of date
//
// A control's key is its enum name with CC_ stripped and the rest camelCased,
// so CC_GEN_FAN_LFO is genFanLfo. That rule is the whole mapping: there is
// no rename table for it to drift against.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const HEADER = join(ROOT, 'shared/aurora_protocol.h');
const OUT = join(ROOT, 'tools/cc.js');

const src = readFileSync(HEADER, 'utf8');

const camel = name =>
  name.replace(/^CC_/, '').toLowerCase()
      .replace(/_(.)/g, (_, c) => c.toUpperCase());

const enumBody = src.slice(src.indexOf('enum AuroraCC'), src.indexOf('};', src.indexOf('enum AuroraCC')));
// The tags live beside each CC in the enum and are read from there, never
// restated here: [patch] and [switch] are what a patch holds, [ambient] and
// [gesture] are what the box reports, and [rate] and [circular] say what a
// modulation route may do with it.
const cc = {};
const tags = {};
for (const m of enumBody.matchAll(/^\s*(CC_[A-Z0-9_]+)\s*=\s*(\d+), *\/\/ *([^\n]*)/gm)) {
  const key = camel(m[1]);
  cc[key] = Number(m[2]);
  tags[key] = [...m[3].matchAll(/\[(\w+)\]/g)].map(t => t[1]);
}
for (const m of enumBody.matchAll(/^\s*(CC_[A-Z0-9_]+)\s*=\s*(\d+),/gm)) {
  const key = camel(m[1]);
  if (!(key in cc)) { cc[key] = Number(m[2]); tags[key] = []; }
}

const one = (re, what) => {
  const m = src.match(re);
  if (!m) throw new Error(`${HEADER}: could not find ${what}`);
  return m[1];
};

const routes = Number(one(/AURORA_ROUTES\s*=\s*(\d+);/, 'AURORA_ROUTES'));
const bases = one(/AURORA_ROUTE_BASE\[AURORA_ROUTES\]\s*=\s*\{([^}]*)\}/s, 'AURORA_ROUTE_BASE')
  .split(',').map(s => s.trim()).filter(Boolean).map(Number);
if (bases.length !== routes) throw new Error('AURORA_ROUTE_BASE does not match AURORA_ROUTES');

const fields = {};
for (const m of src.matchAll(/^\s*(ROUTE_[A-Z]+)\s*=\s*(\d+),/gm)) {
  if (m[1] === 'ROUTE_FIELDS') continue;  // the count, not a field
  fields[camel(m[1].replace(/^ROUTE_/, ''))] = Number(m[2]);
}

const num = (re, what) => Number(one(re, what));
const maxRatio = num(/AURORA_ROUTE_MAX_RATIO\s*=\s*(\d+);/, 'AURORA_ROUTE_MAX_RATIO');
const presetGenerator = num(/PRESET_GENERATOR\s*=\s*(\d+),/, 'PRESET_GENERATOR');
const waveSwell = num(/#define GEN_WAVE_SWELL\s+(\d+)/, 'GEN_WAVE_SWELL');
const waveSawDown = num(/#define GEN_WAVE_SAW_DOWN\s+(\d+)/, 'GEN_WAVE_SAW_DOWN');
const waveSquare = num(/#define GEN_WAVE_SQUARE\s+(\d+)/, 'GEN_WAVE_SQUARE');
const minWidth = one(/#define GEN_LFO_MIN_WIDTH\s+([0-9.]+)f/, 'GEN_LFO_MIN_WIDTH');
const lfoPeriods = one(/AURORA_LFO_PERIODS\[\]\s*=\s*\{([^}]*)\}/s, 'AURORA_LFO_PERIODS')
  .split(',').map(s => s.trim().replace(/f$/, '')).filter(Boolean).map(Number);

const pairs = Object.entries(cc).sort((a, b) => a[1] - b[1]);
const width = Math.max(...pairs.map(([k]) => k.length));
const body = pairs.map(([k, v]) => `    ${k}:${' '.repeat(width - k.length)} ${v},`).join('\n');

const out = `// Generated by tools/gen-cc.mjs from shared/aurora_protocol.h. Do not edit.
//
// Run \`node tools/gen-cc.mjs\` after changing the header; \`--check\` fails if
// this file is stale.

(function (global) {
  'use strict';

  const CC = {
${body}
  };

  const ROUTES = ${routes};
  const ROUTE_BASE = [${bases.join(', ')}];
  const ROUTE_FIELD = ${JSON.stringify(fields)};
  const ROUTE_MAX_RATIO = ${maxRatio};

  const routeCC = (route, field) => ROUTE_BASE[route] + field;

  // Whole multiples only, 1 through ${maxRatio}. Dividing would break the anchor.
  const routeRatio = v =>
    1 + Math.min(ROUTE_MAX_RATIO - 1,
                 Math.floor((v * (ROUTE_MAX_RATIO - 1) + 63) / 127));

  const PRESET_GENERATOR = ${presetGenerator};

  const GEN_WAVE_SWELL = ${waveSwell};
  const GEN_WAVE_SAW_DOWN = ${waveSawDown};
  const GEN_WAVE_SQUARE = ${waveSquare};
  const GEN_LFO_MIN_WIDTH = ${minWidth};

  // Longest first, in animation beats: the LFO's rate and both ramp times
  // step through these.
  const LFO_PERIODS = [${lfoPeriods.join(', ')}];

  const TAGS = ${JSON.stringify(tags)};
  const tagged = tag => Object.keys(TAGS).filter(n => TAGS[tag ? n : n].includes(tag));

  const NAME_BY_CC = {};
  for (const [name, number] of Object.entries(CC)) NAME_BY_CC[number] = name;

  global.AuroraCC = {
    CC, TAGS, tagged, NAME_BY_CC, ROUTES, ROUTE_BASE, ROUTE_FIELD, ROUTE_MAX_RATIO,
    routeCC, routeRatio, PRESET_GENERATOR,
    GEN_WAVE_SWELL, GEN_WAVE_SAW_DOWN, GEN_WAVE_SQUARE, GEN_LFO_MIN_WIDTH,
    LFO_PERIODS,
  };
})(typeof window === 'undefined' ? globalThis : window);
`;

// The renderer cannot read a comment, so routes.cpp restates the tags as
// switches. This is what stops the two from drifting.
function checkRenderer() {
  const src = readFileSync(join(ROOT, 'shared/render/routes.cpp'), 'utf8');
  const cases = fn => {
    const at = src.indexOf(`static bool ${fn}(uint8_t cc)`);
    if (at < 0) throw new Error(`routes.cpp: no ${fn}()`);
    const body = src.slice(at, src.indexOf('\n}', at));
    return new Set([...body.matchAll(/case (CC_[A-Z0-9_]+):/g)].map(m => camel(m[1])));
  };
  const want = {
    refused: new Set(['tempoDivision', 'genLfoRate']),
    swings: new Set(tagged('rate')),
    circular: new Set(tagged('circular')),
    plainLfo: new Set(tagged('plain')),
  };
  const problems = [];
  for (const [fn, expected] of Object.entries(want)) {
    const got = cases(fn);
    for (const n of expected) if (!got.has(n)) problems.push(`${fn}() is missing ${n}`);
    for (const n of got) if (!expected.has(n)) problems.push(`${fn}() has ${n}, which the enum does not tag`);
  }
  return problems;
}

const tagged = tag => Object.keys(tags).filter(n => tags[n].includes(tag));

if (process.argv.includes('--check')) {
  const problems = checkRenderer();
  if (problems.length) {
    for (const line of problems) console.error('shared/render/routes.cpp: ' + line);
    process.exit(1);
  }
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { }
  if (current !== out) {
    console.error('tools/cc.js is out of date — run: node tools/gen-cc.mjs');
    process.exit(1);
  }
  console.log(`tools/cc.js up to date — ${pairs.length} controls, ${routes} routes,`
    + ` and routes.cpp agrees with the enum's tags`);
} else {
  writeFileSync(OUT, out);
  console.log(`tools/cc.js written — ${pairs.length} controls, ${routes} routes`);
}
